### PR TITLE
docs: corrected grammatical errors in README.md

### PR DESCRIPTION
**Pull request by alienishi**
@PWhiddy 
I have corrected several grammatical errors in README.md.

### CODE REVIEW

**Comment by alienishi** [comment]
@PWhiddy 
Please review my PR and if according to the guidelines please do merge it.

**Review by coderunnerone1 — APPROVED** [review]

**Comment by PWhiddy** [comment]
sorry, this very hard to review because most of the changes are not fixes but just changes to alternative phrasing.

**Comment by alienishi** [comment]
@PWhiddy I understand 
any changes you want to suggest am happy to change :)

**Comment by alienishi** [comment]
Hi @PWhiddy 
Thanks for the suggestion I'll keep this in mind closing the PR

**Pull request closed without merging**
