### PR TITLE
Add resume functional from newest run run_baseline_parallel.py

### PR DESCRIPTION
**Pull request by techmore**
Replaces hard coded resume function and adds a function that searches the current folder for the all sessions and finds the newest timestamp and attempts to load it.

It's been tested on Mac and Linux.

### CODE REVIEW

**Review by Bondo-Kyle — COMMENTED** [review]
Tried running this and got error saying name 'os' not defined in line 30 os.listdir()
What am i missing
I am on Mac OS (and a total noob)

**Comment by techmore** [comment]
@Bondo-Kyle can you make sure you have

import os
import glob
import re

added at the top and try again

**Comment by Bondo-Kyle** [comment]
> @Bondo-Kyle can you make sure you have
> 
> import os import glob import re
> 
> added at the top and try again

Yep. I was missing the import os

**Comment by Bondo-Kyle** [comment]
Resolved my import OS issue which led to this issue now
image

**Comment by techmore** [comment]
@Bondo-Kyle Oops. my local machine is little further ahead.. I just pushed out new code that has that function and tensorboard added that I'm running directly.

This code also changes     num_cpu = os.cpu_count() so you may want to set it back to 44 if you prefer that. Could you test it and ensure that error goes away and maybe I'll just try to push this updated coded instead.

[https://raw.githubusercontent.com/techmore/PokemonRedExperiments/patch-1/baselines/run_baseline_parallel.py](url)

**Comment by Bondo-Kyle** [comment]
> @Bondo-Kyle Oops. my local machine is little further ahead.. I just pushed out new code that has that function and tensorboard added that I'm running directly.
> 
> This code also changes num_cpu = os.cpu_count() so you may want to set it back to 44 if you prefer that. Could you test it and ensure that error goes away and maybe I'll just try to push this updated coded instead.
> 
> https://raw.githubusercontent.com/techmore/PokemonRedExperiments/patch-1/baselines/run_baseline_parallel.py

I had to `pip install tensorflow` first, then it started to work again for me. Producing new warnings i hadn't seen before but its back to working. Thank you!

**Pull request closed without merging**
